---
verbose: false
concurrency: 10
pidfile: /home/user/api-project-production/shared/tmp/pids/sidekiq.pid
queues:
  - [critical, 2]
  - default
  - low
production:
  concurrency: 25
staging:
  concurrency: 15
